global: {}

argocd-config:
  repoUrl: ""

  project: <project-name>

  applicationTargets:
    - targetRevision: <git-branch>
      targetNamespace: <cluster-namespace>
      server: <server url> (optional)
      valueFiles: (optional)
        - <value-yaml>
      applications:
        - name: <app-name-1>
        - name: <app-name-2>
        - name: <app-name-3>

    # - targetRevision: ""
    #   targetNamespace: ""
    #   createNamespace: true
    #   server: "" (optional)
    #   valueFiles: (optional)
    #   - values.yaml
    #   applications:
    #   - app1
    #   - name: app1
    #   - name: app1
    #     type: helm
    #   - name: app1
    #     type: helm
    #     path: app1
    #   - name: app2
    #     type: directory
    #   - name: app3
    #     type: plugin
    #     plugin: plugin-name
    #   - name: app4
    #     type: kustomize
    #     path: app4/overlay
